'use strict';
const $=id=>document.getElementById(id);
const pins555=['GND','TRIG','OUT','RESET','CTRL','THR','DISCH','VCC'];
function chipMap(title,pins){let n=pins.length;return `<div class="chip-map"><strong>⌒ ${title} · 윗면</strong>${Array.from({length:n/2},(_,i)=>`<span>${i+1} · ${pins[i]}</span><span>${n-i} · ${pins[n-i-1]}</span>`).join('')}</div>`}
const timerPanel=document.createElement('section');timerPanel.className='panel page-section';timerPanel.dataset.pageSection='step1';timerPanel.innerHTML=`<h2>추가 실험 · 555 타이머</h2><p>게이트가 입력을 판단한다면, 555는 시간을 만들어 줍니다. 여기서는 LED가 반복해서 켜졌다 꺼지는 <b>비안정 발진 모드</b>를 실험합니다. 555는 논리 게이트가 아니므로 위의 진리표와는 별개입니다.</p><div class="lab-grid"><div class="timer-controls"><label>R₁ (kΩ) <input id="r1" type="number" value="10" min="1" max="1000"></label><label>R₂ (kΩ) <input id="r2" type="number" value="68" min="1" max="1000"></label><label>C (µF) <input id="cap" type="number" value="10" min="0.1" max="1000" step="0.1"></label><div class="lab-actions"><button id="timerStart">발진 시작</button><button id="timerStop">정지</button></div></div><div><div class="lab-result"><span id="timerLed" class="bench-led"></span>OUT <span id="timerOut">0</span></div><p id="timerNumbers"></p><p class="lab-small">tHIGH ≈ 0.693(R₁+R₂)C / tLOW ≈ 0.693R₂C<br>f ≈ 1.44 / ((R₁+2R₂)C) · R은 Ω, C는 F로 계산합니다. 높은 주파수는 화면 갱신 속도 때문에 깜빡임을 정확히 볼 수 없습니다.</p></div></div>`;
const quizSection=document.querySelector('.quiz-panel');quizSection.before(timerPanel);
let timerHandle=null,timerRunning=false,timerHigh=false;
function timerValues(){const r1=Math.max(1,Math.min(1000,+$('r1').value||1))*1000,r2=Math.max(1,Math.min(1000,+$('r2').value||1))*1000,c=Math.max(.1,Math.min(1000,+$('cap').value||.1))*1e-6;let hi=.693*(r1+r2)*c,lo=.693*r2*c;$('timerNumbers').textContent=`켜짐 ${hi.toFixed(3)}초 · 꺼짐 ${lo.toFixed(3)}초 · 약 ${(1/(hi+lo)).toFixed(2)} Hz`;return [hi,lo]}
function timerTick(){if(!timerRunning)return;timerHigh=!timerHigh;$('timerOut').textContent=+timerHigh;$('timerLed').classList.toggle('on',timerHigh);const t=timerValues();timerHandle=setTimeout(timerTick,Math.max(30,t[timerHigh?0:1]*1000))}
$('timerStart').onclick=()=>{clearTimeout(timerHandle);timerRunning=true;timerHigh=false;timerTick()};$('timerStop').onclick=()=>{timerRunning=false;clearTimeout(timerHandle);$('timerOut').textContent='0';$('timerLed').classList.remove('on')};['r1','r2','cap'].forEach(id=>$(id).oninput=timerValues);timerValues();
const t2=document.createElement('div');t2.id='timerIC';t2.hidden=true;t2.innerHTML=`<div class="lab-grid">${chipMap('NE555 · DIP-8',pins555)}<div><h3>NE555 타이머 · 핀과 연결</h3><p>5단계의 TLC555는 CMOS형 555 타이머입니다. 기본 핀 구성과 RC 연결은 같지만 출력 전압 등 전기적 규격은 다르므로 실제 부품의 데이터시트를 확인하세요.</p><ol><li>1번 GND, 8번 +5V, 4번 RESET은 +5V에 연결합니다.</li><li>2번 TRIG와 6번 THR를 서로 연결합니다.</li><li>+5V → R₁ → 7번 DISCH → R₂ → 2·6번 순서로 연결합니다.</li><li>2·6번과 GND 사이에 C를 연결합니다. 전해 콘덴서의 +는 2·6번입니다.</li><li>5번 CTRL과 GND 사이에는 10nF, 8번과 1번 사이에는 100nF를 연결합니다.</li><li>3번 OUT → 1kΩ → LED 애노드(+), LED 캐소드(−) → GND로 연결합니다.</li></ol><p>콘덴서가 충전·방전을 반복하면 3번에서 HIGH/LOW가 반복됩니다. TRIG가 전원의 1/3보다 낮아지면 출력을 HIGH로, THR가 2/3보다 높아지면 LOW로 바꿉니다. RESET=0은 출력을 LOW로 만듭니다.</p><p class="lab-small">NE555 출력의 HIGH 전압은 전원과 정확히 같지 않습니다. 74HC 입력과 직접 연결할 때는 실제 HIGH 규격을 확인하고 필요하면 버퍼 또는 CMOS 555를 사용하세요.</p></div></div>`;
$('step2').append(t2);const timerBtn=document.createElement('button');timerBtn.className='ic-btn';timerBtn.textContent='NE555 타이머';$('icButtons').append(timerBtn);timerBtn.onclick=()=>{document.querySelector('#step2 .ic-layout').hidden=true;document.querySelector('#step2 .ic-layout').style.display='none';t2.hidden=false;document.querySelectorAll('.ic-btn').forEach(b=>b.classList.toggle('active',b===timerBtn))};document.querySelectorAll('.ic-btn[data-ic]').forEach(b=>b.addEventListener('click',()=>{t2.hidden=true;document.querySelector('#step2 .ic-layout').style.display='';document.querySelector('#step2 .ic-layout').hidden=false;timerBtn.classList.remove('active')}));
const easy={
'반가산기':['1비트 덧셈은 작은 덧셈입니다. 0+0=0, 0+1=1, 1+0=1입니다. 그런데 1+1=2는 이진수로 10이라 출력 두 개가 필요합니다.','오른쪽 자리 Sum은 XOR로, 왼쪽 자리 Carry는 AND로 만듭니다. A=1, B=1을 넣으면 Sum=0, Carry=1 → 10₂가 됩니다.'],
'전가산기':['세 수를 더하는 덧셈 블록입니다. A와 B는 이번 자리의 숫자이고 Cin은 바로 아래 자리에서 올라온 1입니다.','먼저 A와 B를 더하고, 그 합에 Cin을 더합니다. A=1, B=0, Cin=1이면 총 2이므로 Sum=0, Cout=1입니다. 전가산기 4개를 연결하면 4비트 덧셈기가 됩니다.'],
'멀티플렉서':['여러 TV 채널 중 하나를 고르는 선택기라고 생각하세요. 데이터 입력은 채널, 선택선 S는 리모컨입니다.','2:1 MUX에서 S=0이면 D0, S=1이면 D1이 출력됩니다. D0=0, D1=1일 때 S만 바꾸어도 출력이 0에서 1로 바뀝니다.'],
'디멀티플렉서':['하나의 물줄기를 여러 길 중 한 곳으로 보내는 수도꼭지입니다. 입력은 하나, 목적지는 여러 개입니다.','1:2 예에서 D=1, S=0이면 Y0=1·Y1=0, S=1이면 Y0=0·Y1=1입니다. 선택되지 않은 출력은 0이라고 가정한 예입니다.'],
'D 플립플롭':['버튼을 누르는 순간 사진을 찍듯이, 지정된 클록 순간에 입력 D를 기억합니다.','상승 에지형에서 D=1일 때 CLK가 0→1로 바뀌면 Q=1입니다. 이후 D가 0으로 변해도 다음 상승 에지 전까지 Q는 1을 유지합니다.'],
'JK 플립플롭':['현재 상태를 기억하면서 명령 두 개 J와 K를 받습니다. 유효 클록 에지에서 00=유지, 10=1로 설정, 01=0으로 설정, 11=뒤집기입니다.','J=K=1을 고정하면 클록마다 Q가 0→1→0으로 반복됩니다. 실제 IC에 따라 상승/하강 에지 조건이 다르니 데이터시트를 확인합니다.'],
'T 플립플롭':['T는 Toggle(뒤집기)의 약자입니다. T=0이면 현재 상태를 유지하고 T=1이면 유효 클록 때마다 반대로 바뀝니다.','처음 Q=0이고 T=1이면 클록 1회 후 1, 2회 후 0, 3회 후 1입니다. 따라서 출력은 입력 클록의 절반 주파수가 됩니다.'],
'동기식 10진 카운터':['카운터는 펄스가 몇 번 왔는지 세는 장치입니다. 10진 카운터는 0→1→…→9 다음에 0으로 돌아옵니다.','동기식은 모든 기억 소자가 같은 클록을 받습니다. 함께 출발하는 달리기 선수처럼 자리들이 같은 기준 순간에 갱신됩니다. 9 다음 자리로 넘기는 신호를 연결하면 두 자리 숫자를 셉니다.'],
'비동기식 10진 카운터':['비동기식은 앞 소자의 변화가 다음 소자를 움직입니다. 도미노가 차례로 넘어지는 모습과 비슷합니다.','연결은 비교적 단순하지만 각 자리 변화 사이에 작은 지연이 생깁니다. 여러 비트를 동시에 읽는 회로에서는 잠깐 나타나는 중간값에 주의합니다.']};
document.querySelectorAll('#step3 .concept-card').forEach(card=>{const title=card.querySelector('h3').textContent;if(easy[title]){const old=card.querySelector('p:not(.formula)');old.innerHTML=`<b>쉽게 생각하면</b><br>${easy[title][0]}<br><br><b>숫자로 확인하기</b><br>${easy[title][1]}`}});
const segCard=[...document.querySelectorAll('#step3 .concept-card')].find(c=>c.querySelector('h3').textContent==='7세그먼트');
function segSvg(digit='8'){const on=['abcdef','bc','abdeg','abcdg','bcfg','acdfg','acdefg','abc','abcdefg','abcdfg'][+digit]||'';const coords={a:[95,35,70,13],b:[166,50,13,58],c:[166,126,13,58],d:[95,186,70,13],e:[80,126,13,58],f:[80,50,13,58],g:[95,111,70,13]};return `<svg viewBox="0 0 260 230" role="img" aria-label="다리 없는 7세그먼트 표시부"><rect x="58" y="20" width="145" height="194" rx="16" fill="#172033"/>${Object.entries(coords).map(([s,c])=>`<rect x="${c[0]}" y="${c[1]}" width="${c[2]}" height="${c[3]}" rx="4" fill="${on.includes(s)?'#34d399':'#475569'}"/><text x="${c[0]+(c[2]>20?30:2)}" y="${c[1]+(c[2]>20?11:35)}" font-size="11" fill="#fff">${s}</text>`).join('')}<text x="216" y="110" font-size="12" fill="#334155">숫자</text></svg>`}
segCard.querySelector('.seven-display').outerHTML=`<div class="seg-demo"><div id="segPicture">${segSvg()}</div><div><label>표시 숫자 <select id="segDigit">${Array.from({length:10},(_,i)=>`<option ${i===8?'selected':''}>${i}</option>`).join('')}</select></label><p>공통 캐소드(CC): COM → GND, a~g가 HIGH면 켜짐.<br>공통 애노드(CA): COM → +전원, a~g가 LOW면 켜짐.</p><p class="lab-small">표시부만 보여 주며 다리 모양은 생략했습니다. 실제 10핀 제품의 물리 핀 번호·COM 개수·DP 위치는 모델마다 다릅니다. 실제 연결은 해당 표시기의 데이터시트를 확인하세요.</p></div></div>`;
$('segDigit').onchange=()=>$('segPicture').innerHTML=segSvg($('segDigit').value);
// Four: six chip experiments, including the nonstandard input/output pins.
const benchTypes={AND:['7408',[1,2],3],OR:['7432',[1,2],3],NOT:['7404',[1],2],NAND:['7400',[1,2],3],NOR:['7402',[2,3],1],XOR:['7486',[1,2],3]};let bt='AND',ba=0,bb=0,bstep=0;
function renderBench(){const [num,ins,out]=benchTypes[bt],data=icData[bt],labels=[...data.pins.slice(0,6),'GND',...data.pins.slice(6),'VCC'];$('benchTabs').innerHTML=Object.entries(benchTypes).map(([k,v])=>`<button class="${k===bt?'active':''}" data-bench="${k}">${v[0]} ${k}</button>`).join('');$('benchTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{bt=b.dataset.bench;bstep=0;ba=bb=0;renderBench()});$('bench').innerHTML=`<div class="lab-grid"><div class="lab-box"><h3>${num} · ${bt} 연결 순서</h3><ol><li>전원을 끈 상태에서 IC를 브레드보드 중앙 홈을 가로질러 꽂습니다. 홈/점이 1번 방향입니다.</li><li><b>7번 → GND, 14번 → +5V</b>를 연결합니다. 두 전원 핀 사이에 100nF 바이패스 콘덴서를 둡니다.</li><li><b>${out}번 출력 → 1kΩ → LED 애노드(+)</b>, LED 캐소드(−) → GND로 연결합니다.</li><li>${ins.map((pin,i)=>`${pin}번 ${i?'B':'A'} 입력`).join(', ')}에 스위치로 GND(0) 또는 +5V(1)를 넣습니다. 빈 입력으로 두지 마세요.</li><li>입력을 바꾸어 LED와 아래 진리표를 비교합니다.</li></ol><p>${data.desc} ${gateInfo[bt].description}</p></div><div>${chipMap(num,labels)}<div class="lab-actions"><button id="benchNext">${['① IC 꽂기','② 전원 연결','③ 저항·LED 연결','④ 입력 스위치 연결','연결 완료'][bstep]}</button><button id="benchReset">처음부터</button></div><p class="lab-status">진행 ${bstep}/4 · ${bstep===4?'전원 ON · 입력을 바꾸세요.':'위 순서를 읽고 연결 버튼을 누르세요.'}</p><div id="benchInputs" class="lab-actions">${ins.map((pin,i)=>`<span>${pin}번 ${i?'B':'A'}: <button class="lab-button" data-bit="${i}">${i?bb:ba} → 바꾸기</button></span>`).join('')}</div><div class="lab-result"><span class="bench-led ${bstep===4&&calculate(bt,ba,bb)?'on':''}"></span>${out}번 Y = ${bstep===4?calculate(bt,ba,bb):'—'}</div><div class="table-scroll"><table class="lab-table"><tr><th>A</th>${ins.length===2?'<th>B</th>':''}<th>Y</th></tr>${(ins.length===1?[[0,0],[1,0]]:[[0,0],[0,1],[1,0],[1,1]]).map(([a,b])=>`<tr><td>${a}</td>${ins.length===2?`<td>${b}</td>`:''}<td>${calculate(bt,a,b)}</td></tr>`).join('')}</table></div></div></div><p class="lab-notice lab-warn">실물 권장: 5V 74HC 계열(74HC08/32/04/00/02/86)을 동일 계열로 사용하세요. 7408 등의 표기는 논리 기능 번호입니다. 74LS의 HIGH 출력은 LED 직접 구동 및 HC 입력과의 호환성이 다르므로 이 회로를 그대로 적용하지 말고 버퍼·트랜지스터와 전기적 규격을 확인하세요. 사용하지 않는 입력은 일정한 0/1로 고정하고 출력끼리는 연결하지 않습니다.</p>`;$('benchNext').disabled=bstep===4;$('benchNext').onclick=()=>{bstep++;renderBench()};$('benchReset').onclick=()=>{bstep=ba=bb=0;renderBench()};$('benchInputs').querySelectorAll('button').forEach(b=>{b.disabled=bstep!==4;b.onclick=()=>{if(b.dataset.bit==='0')ba^=1;else bb^=1;renderBench()}})}renderBench();
// Five: guided digital netlist experiments. Every project has its own parts and required connections.
const P=(id,name,ports)=>({id,name,ports:ports.split('|')});
const commonParts=[P('power','안정화 +5V 전원','5V|GND')];
function displayParts(n){return Array.from({length:n},(_,i)=>[P('dec'+i,`CD4511 ${i+1} · BCD 디코더`,'VCC16|GND8|A7|B1|C2|D6|a13|b12|c11|d10|e9|f15|g14'),P('seg'+i,`CC 7세그먼트 ${i+1}`,'COM|a|b|c|d|e|f|g')]).flat()}
function powerWires(parts){return parts.flatMap(p=>p.ports.filter(v=>v.startsWith('VCC')||v.startsWith('GND')).map(pin=>[`power.${pin.startsWith('VCC')?'5V':'GND'}`,`${p.id}.${pin}`]))}
function displayWires(n,counters){let w=[];for(let i=0;i<n;i++){w.push(['power.GND',`seg${i}.COM`]);['a','b','c','d','e','f','g'].forEach((s,j)=>w.push([`dec${i}.${['a13','b12','c11','d10','e9','f15','g14'][j]}`,`seg${i}.${s}`]));['QA3','QB2','QC6','QD7'].forEach((s,j)=>w.push([`${counters[i]}.${s}`,`dec${i}.${['A7','B1','C2','D6'][j]}`]))}return w}
const countPart=(id,label)=>P(id,label,'VCC16|GND8|UP5|DOWN4|QA3|QB2|QC6|QD7|CARRY12|BORROW13');
const clockPart=P('clock','TLC555 · 발진 회로','VCC8|GND1|OUT3');
const projects=[
{name:'2자리 디지털 스톱워치',tag:'00 → 99 · 1초씩 측정',parts:[...commonParts,clockPart,P('control','74HC08 · 시작/정지 게이트','VCC14|GND7|CLK1|RUN2|Y3'),P('run','START/STOP 스위치','OUT'),countPart('u','74HC192 · 일의 자리'),countPart('t','74HC192 · 십의 자리'),...displayParts(2)],wires:[['clock.OUT3','control.CLK1'],['run.OUT','control.RUN2'],['control.Y3','u.UP5'],['u.CARRY12','t.UP5']],countIds:['u','t'],steps:['TLC555를 비안정 모드로 구성해 약 1Hz를 만듭니다. R₁=10kΩ, R₂=68kΩ, C=10µF이면 약 0.99Hz입니다. 정밀 시계용이 아니라 학습용 근사값입니다.','555 OUT(3) → 74HC08 입력 1, RUN 스위치 → 입력 2, 출력 3 → 일의 자리 74HC192 UP(5)을 연결합니다. RUN=1에서만 펄스가 통과합니다.','일의 자리 CARRY(12) → 십의 자리 UP(5)을 연결합니다. 두 카운터의 DOWN(4)은 HIGH로 고정합니다. 9 다음 0이 될 때 십의 자리가 증가합니다.','각 카운터 QA/QB/QC/QD를 각 CD4511 A/B/C/D에 연결하고, 디코더의 a~g는 저항을 거쳐 공통 캐소드 표시기로 보냅니다.','MR(14)을 잠깐 HIGH로 만들면 00으로 초기화합니다. 시작·정지 후 재시작하면 이어서 셉니다. 99 다음 00으로 돌아갑니다.']},
{name:'주차장 관리 시스템',tag:'입차 · 출차 · 현재 주차 · 잔여 공간 (정원 99대)',parts:[...commonParts,P('sensors','입차·출차 감지 버튼','IN|OUT'),P('parking','74HC14·08·32 · 입출차 제어 블록','VCC14|GND7|IN|OUT|UP|DOWN|BCD_U|BCD_T'),countPart('u','74HC192 · 주차 일의 자리'),countPart('t','74HC192 · 주차 십의 자리'),...displayParts(2)],wires:[['sensors.IN','parking.IN'],['sensors.OUT','parking.OUT'],['parking.UP','u.UP5'],['parking.DOWN','u.DOWN4'],['u.CARRY12','t.UP5'],['u.BORROW13','t.DOWN4'],['u.QA3','parking.BCD_U'],['t.QA3','parking.BCD_T']],countIds:['u','t'],steps:['입차 버튼은 차량 1대 진입, 출차 버튼은 차량 1대 퇴장을 나타냅니다. 접점 튐을 제거한 펄스를 사용합니다.','입출차 제어 블록은 두 클록을 평소 HIGH로 유지합니다. 입차 시 UP에 LOW→HIGH 펄스, 출차 시 DOWN에 LOW→HIGH 펄스를 보내며 반대 클록은 HIGH를 유지합니다. 두 센서의 동시 입력은 중재 회로가 필요합니다.','일의 자리 CARRY(12)→십의 자리 UP(5), BORROW(13)→십의 자리 DOWN(4)을 연결해 00~99를 셉니다.','각 자리 QA~QD를 CD4511 A~D로 보내 현재 주차 대수를 표시합니다. BCD_U/T는 각 4비트 묶음이며 화면 QA 연결은 묶음의 대표선입니다.','제어 블록은 00에서 출차, 99에서 입차 펄스를 차단합니다. 웹은 누적 입차·출차와 잔여 공간도 계산합니다. 실물 누적 집계는 별도 카운터와 표시기가 필요하며 경계 검출·중재·펄스 성형 회로는 별도로 설계해야 합니다.']},
{name:'반응속도 측정 게임기',tag:'준비 → GO → 반응 · 10ms 단위',parts:[...commonParts,clockPart,P('ctrl','74HC74·08 제어 블록','VCC14|GND7|GO|REACT|CLK|COUNT|READY'),P('buttons','GO/반응 버튼','GO|REACT'),P('ready','GO LED + 1kΩ','IN'),countPart('u','74HC192 · 0.01초'),countPart('t','74HC192 · 0.1초'),...displayParts(2)],wires:[['clock.OUT3','ctrl.CLK'],['buttons.GO','ctrl.GO'],['buttons.REACT','ctrl.REACT'],['ctrl.READY','ready.IN'],['ctrl.COUNT','u.UP5'],['u.CARRY12','t.UP5']],countIds:['u','t'],steps:['TLC555를 약 100Hz로 만듭니다. 예: R₁=10kΩ, R₂=68kΩ, C=0.1µF → 약 98.6Hz. 실제 측정 정확도는 부품 오차에 좌우됩니다. 화면 모형은 10ms 단위로 계산합니다.','실물 기본형은 진행자가 GO 버튼을 누릅니다. 웹에서는 준비 후 1~3초 무작위로 GO가 켜집니다. 이 무작위 대기는 브라우저 기능으로, 실물에는 별도 랜덤 지연 회로가 필요합니다.','GO로 74HC74의 RUN 상태를 1로 설정하고 반응 버튼으로 0으로 만듭니다. 74HC08이 RUN=1일 때만 100Hz 펄스를 카운터로 통과시킵니다.','카운터와 표시기는 스톱워치와 같은 BCD 연결을 사용합니다. 00~99는 0.00~0.99초입니다. 1초 이상은 웹에서 범위 초과로 표시하며 실물에는 별도 오버플로 래치가 필요합니다.','GO 전에 반응 버튼을 누르면 부정 출발입니다. 웹 모형은 이를 판정하지만 실물에는 조기 입력 검출 래치가 추가로 필요합니다.']},
{name:'카운트다운 신호등 제어기',tag:'빨강 10초 → 초록 10초 → 노랑 3초',parts:[...commonParts,clockPart,P('fsm','74HC74·00·08·32 제어 블록','VCC14|GND7|CLK|COUNT|ZERO|R|Y|G'),countPart('u','74HC192 · 일의 자리'),countPart('t','74HC192 · 십의 자리'),P('zero','74HC02·32 · 00 검출','VCC14|GND7|BCD_U|BCD_T|ZERO'),P('lights','신호 LED + 저항 ×3','R|Y|G'),...displayParts(2)],wires:[['clock.OUT3','fsm.CLK'],['fsm.COUNT','u.DOWN4'],['u.BORROW13','t.DOWN4'],['u.QA3','zero.BCD_U'],['t.QA3','zero.BCD_T'],['zero.ZERO','fsm.ZERO'],['fsm.R','lights.R'],['fsm.Y','lights.Y'],['fsm.G','lights.G']],countIds:['u','t'],steps:['1Hz 클록으로 74HC192의 DOWN(4)을 구동합니다. 일의 자리 BORROW(13)를 십의 자리 DOWN(4)에 연결하고 UP(5)은 HIGH에 둡니다.','병렬 로드로 빨강·초록은 10, 노랑은 03을 넣습니다. 74HC192 A(15), B(1), C(10), D(9)에 값의 BCD를 설정하고 /PL(11)을 LOW로 펄스 입력합니다.','8개의 카운터 출력이 전부 0인지 OR→NOT으로 검출합니다. 화면의 BCD_U/T 단자는 각각 QA~QD 4선 묶음을 뜻하며 QA 한 선만으로 00을 검출하면 안 됩니다.','상태 00=빨강, 01=초록, 10=노랑으로 74HC74 두 비트에 저장합니다. ZERO일 때만 다음 상태로 넘기고 해당 시간을 다시 로드합니다.','신호등은 세 상태 중 하나만 켜지도록 디코딩합니다. 이 웹의 FSM은 기능 블록입니다. 실물에는 다음 상태 논리, 안정된 로드 펄스 및 00 검출 글리치 방지 회로를 추가 설계해야 합니다.']},
{name:'777 룰렛 만들기',tag:'세 자리 순차 정지 · 777 당첨',parts:[...commonParts,clockPart,P('gates','74HC08 · 3채널 클록 제어','VCC14|GND7|CLK|RUN0|RUN1|RUN2|Y0|Y1|Y2'),P('stops','시작·정지 스위치','RUN0|RUN1|RUN2'),...Array.from({length:3},(_,i)=>countPart('c'+i,`74HC192 · ${i+1}번째 자리`)),...displayParts(3)],wires:[['clock.OUT3','gates.CLK'],...[0,1,2].flatMap(i=>[[`stops.RUN${i}`,`gates.RUN${i}`],[`gates.Y${i}`,`c${i}.UP5`]])],countIds:['c0','c1','c2'],steps:['TLC555로 수십 Hz의 클록을 만들고 74HC08 게이트 세 개의 한쪽 입력에 공통으로 연결합니다. 각 다른 입력에는 RUN 스위치를 연결합니다.','게이트 세 출력은 각 74HC192 UP(5)로 보냅니다. 여기서는 세 카운터를 자리올림으로 연결하지 않습니다. 각 자리가 0~9를 독립적으로 반복합니다.','카운터마다 CD4511 한 개와 공통 캐소드 표시기 한 개를 연결합니다. a~g마다 개별 저항이 필요하므로 세 자리에는 총 21개입니다.','시작하면 세 자리 RUN=1, 정지1·정지2·정지3을 누르면 해당 자리 RUN=0으로 만들어 숫자를 고정합니다.','세 자리가 모두 7이면 당첨입니다. 실물 자동 판정은 각 자리에서 QA·QB·QC·NOT(QD)를 검출하고 세 검출 출력을 AND로 묶습니다(74HC04·08 추가). 웹은 이 판정을 직접 수행합니다. 이 모형은 난수 슬롯머신이 아니라 타이밍 실험입니다.']}
];
projects.forEach(p=>{p.wires.push(...powerWires(p.parts));if(p.countIds)p.wires.push(...displayWires(p.countIds.length,p.countIds))});
let pi=0,placed={},connections=[],pending=null,simulation=null,simState={},selectedWire=-1;
function wireKey(a,b){return [a,b].sort().join('~')}
function safeStop(){if(simulation){clearInterval(simulation);clearTimeout(simulation)}simulation=null}
function saveWork(){try{localStorage.setItem('logicLabV4_'+pi,JSON.stringify({placed,connections}))}catch(e){}}
function loadWork(){placed={};connections=[];try{const s=JSON.parse(localStorage.getItem('logicLabV4_'+pi));if(s){placed=s.placed||{};connections=s.connections||[]}}catch(e){}}
const safety=`<div class="lab-notice lab-warn"><b>가상 회로의 범위</b> · 이 실험은 지정한 디지털 연결을 검사하는 교육용 모형입니다. 전압·전류·아날로그 파형이나 임의 회로를 해석하는 SPICE 시뮬레이터가 아닙니다. 부품 이동은 배치 연습이며 단자 클릭으로 배선합니다. 화면의 디코더↔표시기 선에는 <b>세그먼트별 1kΩ 저항이 내장된 것으로</b> 모델링합니다. 실물에서는 반드시 별도 저항을 넣으세요. 기능 블록의 내부 배선과 고정 제어 핀은 아래 안내를 참고하세요.</div>`;
function renderProject(){safeStop();pending=null;simState={};loadWork();$('projectTabs').innerHTML=projects.map((p,i)=>`<button class="${i===pi?'active':''}" data-project="${i}">${i+1}. ${p.name}</button>`).join('');$('projectTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{saveWork();pi=+b.dataset.project;renderProject()});const p=projects[pi];$('projectArea').innerHTML=`<h3>${p.name}</h3><p class="formula">${p.tag}</p>${safety}<div class="lab-grid"><div class="lab-box"><h3>준비물</h3><ul><li>${p.parts.filter(x=>x.id!=='power').map(x=>x.name).join(' / ')}</li><li>브레드보드, 점퍼선, 안정화 5V 전원</li><li>각 IC 전원에 100nF × IC 수, 스위치 풀업/풀다운 10kΩ, 버튼 디바운스 회로</li><li>공통 캐소드 표시기 ${p.countIds.length}개 및 세그먼트 1kΩ 저항 ${p.countIds.length*7}개${pi===1?' · 입출차 센서/버튼 2개':' · 555용 R₁·R₂·C 및 10nF'}</li></ul></div><div class="lab-box"><h3>만들기 순서</h3><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div></div><details><summary>실제 IC 핀 번호와 고정 제어 핀 · 반드시 펼쳐 읽기</summary>${pinGuide()}</details><details><summary>프로젝트 연결 목록 (${p.wires.length}개)</summary><div class="table-scroll"><table class="lab-table"><tr><th>출발 단자</th><th>도착 단자</th></tr>${p.wires.map(([a,b])=>`<tr><td>${portLabel(a)}</td><td>${portLabel(b)}</td></tr>`).join('')}</table></div></details><h3>① 재료를 작업대로 옮기기</h3><p class="lab-small">재료를 끌어 놓거나 [추가]를 누르세요. 보드 안에서는 부품의 남색 제목을 드래그합니다. 모바일에서는 [추가] 후 제목을 터치해 이동하세요.</p><div id="materials"></div><div class="lab-actions"><button id="placeAll">재료 모두 배치</button><button id="sampleWiring">모범 배선 불러오기</button><button id="checkWiring">배선 검사</button><button id="undoWire">마지막 배선 취소</button><button id="clearWiring">배선만 지우기</button><button id="resetProject">현재 프로젝트 초기화</button></div><p id="wiringStatus" class="lab-status" aria-live="polite"></p><div id="connectionInfo" class="connection-info" role="status">부품 제목이나 단자에 마우스를 올리거나 키보드 초점을 맞추면 실제 연결 정보가 표시됩니다.</div><div class="lab-board-wrap"><div id="labBoard" class="lab-board"><svg id="projectWires" class="wire-svg"></svg></div></div><p class="lab-small">② 출발 단자를 클릭한 뒤 도착 단자를 클릭하면 연결됩니다. 같은 연결을 한 번 더 선택하면 삭제됩니다. 잘못된 배선이 있으면 실행을 막고 수정할 연결을 알려줍니다. 배선은 이 브라우저에 자동 저장됩니다.</p><h3>③ 동작 실험</h3><div id="simControls" class="lab-actions"></div><div id="simDisplay" class="lab-result" aria-live="polite">배선 검사 후 시작</div><p id="simMessage" class="lab-status"></p>`;
$('materials').innerHTML=p.parts.map(x=>`<div class="material" draggable="true" data-part="${x.id}">${x.name}<button data-add="${x.id}">추가</button></div>`).join('');$('materials').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addPart(b.dataset.add));$('materials').querySelectorAll('[draggable]').forEach(m=>m.ondragstart=e=>e.dataTransfer.setData('text/plain',m.dataset.part));const board=$('labBoard');board.ondragover=e=>e.preventDefault();board.ondrop=e=>{e.preventDefault();const r=board.getBoundingClientRect();addPart(e.dataTransfer.getData('text/plain'),e.clientX-r.left,e.clientY-r.top)};
$('placeAll').onclick=()=>{p.parts.forEach((x,i)=>{if(!placed[x.id])placed[x.id]={x:20+(i%5)*195,y:50+Math.floor(i/5)*180}});drawBoard();saveWork()};$('sampleWiring').onclick=()=>{if(!confirm('현재 배선을 모범 배선으로 바꿀까요?'))return;safeStop();p.parts.forEach((x,i)=>placed[x.id]={x:20+(i%5)*195,y:50+Math.floor(i/5)*180});connections=p.wires.map(w=>[...w]);drawBoard();saveWork();checkWiring()};$('checkWiring').onclick=checkWiring;$('undoWire').onclick=()=>{safeStop();connections.pop();drawBoard();saveWork();checkWiring()};$('clearWiring').onclick=()=>{if(confirm('배선을 모두 지울까요?')){safeStop();connections=[];pending=null;drawBoard();saveWork();checkWiring()}};$('resetProject').onclick=()=>{if(confirm('현재 프로젝트의 배치와 배선을 초기화할까요?')){safeStop();placed={};connections=[];pending=null;saveWork();drawBoard();checkWiring()}};drawBoard();renderSim();checkWiring();}
function portLabel(s){const [id,pin]=s.split('.');const p=projects[pi].parts.find(x=>x.id===id);return `${p?p.name:id} · ${pin}`}
function pinGuide(){return `<div class="lab-notice">핀 번호는 아래 명시한 DIP 제품 기준입니다. 실제 부품의 제조사·패키지 데이터시트를 먼저 확인하세요. 74xx 기능 번호가 같아도 HC/LS 혼용은 전압 호환성을 확인해야 합니다. 버튼 접점 튐은 RC+74HC14 등으로 제거하고, 실제 클록 게이팅은 클록 LOW 동안 RUN을 변경하도록 설계해야 가짜 펄스를 막을 수 있습니다.</div><div class="table-scroll"><table class="lab-table"><tr><th>IC</th><th>연결 기준</th></tr><tr><td>TLC555 DIP-8</td><td>1=GND, 8=VCC, 4=RESET(HIGH), 2·6 연결, 7=방전, 5=10nF→GND, 3=OUT. 저항·콘덴서 연결은 2단계 NE555 안내와 같으며 로직 호환성을 위해 CMOS TLC555 권장. 보드의 555 블록은 RC 부품 포함.</td></tr><tr><td>74HC192 DIP-16</td><td>16=VCC, 8=GND. QA/QB/QC/QD=3/2/6/7. UP=5, DOWN=4. CARRY=12, BORROW=13(LOW 활성). /PL=11은 평소 HIGH, MR=14는 평소 LOW·초기화 시 HIGH. 병렬 A/B/C/D=15/1/10/9. 병렬 입력은 기본 0에 고정. 업 카운트는 DOWN=1, 다운 카운트는 UP=1. 이 고정 제어 핀은 화면에서 생략.</td></tr><tr><td>CD4511 DIP-16</td><td>16=VDD, 8=VSS(GND). BCD A/B/C/D=7/1/2/6. a/b/c/d/e/f/g=13/12/11/10/9/15/14. LE(5)=LOW, /BI(4)=HIGH, /LT(3)=HIGH. 공통 캐소드 표시기 사용. 각 출력→개별 저항→해당 a~g, COM→GND. 표시기의 다리 번호는 제품별 확인. 보드에서는 고정 제어 핀과 저항을 생략하여 표시.</td></tr><tr><td>74HC86 / 74HC08</td><td>14=VCC, 7=GND. 게이트별 (입력,입력→출력)=(1,2→3), (4,5→6), (9,10→8), (12,13→11). 룰렛 HC08은 각 첫 입력=클록, 두 번째 입력=RUN, 출력=카운터.</td></tr><tr><td>74HC74 DIP-14</td><td>14=VCC, 7=GND. 첫 FF: /CLR1, D2, CLK3, /PRE4, Q5, /Q6. 둘째 FF: /Q8, Q9, /PRE10, CLK11, D12, /CLR13. 비동기 /PRE와 /CLR는 LOW 활성, 평소 HIGH이며 둘 다 LOW로 만들지 않습니다. 반응게임·신호등 제어 블록의 핀 이름은 기능 단자이며 완성된 실물 핀 배선도를 뜻하지 않습니다.</td></tr></table></div><p class="lab-small">실물 제작 범위: 스톱워치·룰렛은 위 핀 대응을 사용해 기본 기능을 구성합니다. 주차장의 경계 검출·입출차 중재·누적 집계, 반응게임의 자동 랜덤 대기/부정출발 판정과 신호등의 FSM·자동 로드 회로는 기능 수준 안내이며, 바로 제작 가능한 전체 핀 배선도는 아닙니다. 실제 실험은 교사 지도 아래 전원을 끈 상태에서 배선하고 단락을 확인한 뒤 켜세요.</p>`}
function addPart(id,x,y){const i=projects[pi].parts.findIndex(p=>p.id===id);if(i<0)return;placed[id]={x:Math.max(0,Math.min(825,x??20+(i%5)*195)),y:Math.max(40,Math.min(560,y??50+Math.floor(i/5)*180))};drawBoard();saveWork()}
function drawBoard(){const board=$('labBoard');board.querySelectorAll('.lab-node').forEach(n=>n.remove());projects[pi].parts.filter(p=>placed[p.id]).forEach(p=>{let n=document.createElement('div');n.className='lab-node';n.style.left=placed[p.id].x+'px';n.style.top=placed[p.id].y+'px';n.dataset.node=p.id;n.innerHTML=`<div class="node-head" tabindex="0" title="${connectionText(p.id)}">${p.name}</div><div class="node-ports">${p.ports.map(port=>{const key=p.id+'.'+port;return `<button class="node-port ${pending===key?'selected':''} ${connections.some(w=>w.includes(key))?'connected':''}" data-port="${key}" title="${connectionText(key)}">${port}</button>`}).join('')}</div>`;board.append(n);n.querySelectorAll('.node-port,.node-head').forEach(el=>{const key=el.dataset.port||p.id;el.onmouseenter=el.onfocus=()=>inspectConnection(key);el.onmouseleave=el.onblur=()=>inspectConnection(null)});n.querySelectorAll('button').forEach(b=>b.onclick=()=>pickPort(b.dataset.port));const head=n.querySelector('.node-head');head.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();head.setPointerCapture(e.pointerId);const start={x:e.clientX,y:e.clientY,...placed[p.id]},ox=placed[p.id].x,oy=placed[p.id].y,sx=e.clientX,sy=e.clientY;head.onpointermove=ev=>{placed[p.id]={x:Math.max(0,Math.min(825,ox+ev.clientX-sx)),y:Math.max(40,Math.min(560,oy+ev.clientY-sy))};n.style.left=placed[p.id].x+'px';n.style.top=placed[p.id].y+'px';drawWires()};head.onpointerup=()=>{head.onpointermove=null;saveWork()};head.onpointercancel=()=>{head.onpointermove=null;saveWork()}}});requestAnimationFrame(drawWires)}
function pickPort(port){if(!pending){pending=port;$('wiringStatus').textContent=`선택: ${portLabel(port)} → 연결할 단자를 누르세요.`}else if(pending===port){pending=null}else{safeStop();const k=wireKey(pending,port),i=connections.findIndex(w=>wireKey(...w)===k);if(i>=0)connections.splice(i,1);else connections.push([pending,port]);pending=null;saveWork();checkWiring()}drawBoard()}
function drawWires(){const board=$('labBoard');if(!board)return;const r=board.getBoundingClientRect();$('projectWires').innerHTML=connections.map(([a,b],index)=>{const aEl=board.querySelector(`[data-port="${a}"]`),bEl=board.querySelector(`[data-port="${b}"]`);if(!aEl||!bEl)return '';let ra=aEl.getBoundingClientRect(),rb=bEl.getBoundingClientRect();const x1=ra.x-r.x+ra.width/2,y1=ra.y-r.y+ra.height/2,x2=rb.x-r.x+rb.width/2,y2=rb.y-r.y+rb.height/2;return `<path data-wire="${index}" d="M${x1},${y1} C${x1},${y1+45} ${x2},${y2+45} ${x2},${y2}"/>`}).join('')}
function wiringIssues(){const p=projects[pi],keys=new Set(connections.map(w=>wireKey(...w))),expected=new Set(p.wires.map(w=>wireKey(...w)));return {absent:p.parts.filter(x=>!placed[x.id]),missing:p.wires.filter(w=>!keys.has(wireKey(...w))),extra:connections.filter(w=>!expected.has(wireKey(...w)))}}
function checkWiring(){const a=wiringIssues(),ok=!a.absent.length&&!a.missing.length&&!a.extra.length;$('wiringStatus').textContent=ok?'✓ 배치·배선 완료! 이제 아래에서 동작을 실험하세요.':`미배치 ${a.absent.length}개 · 누락 배선 ${a.missing.length}개 · 다른 연결 ${a.extra.length}개. ${a.extra.length?'수정: '+a.extra.slice(0,2).map(w=>w.map(portLabel).join(' ↔ ')).join(' / '):a.missing.length?'다음 연결: '+a.missing[0].map(portLabel).join(' → '):''}`;return ok}
function canRun(){if(checkWiring())return true;$('simMessage').textContent='먼저 재료를 배치하고 누락/잘못된 연결을 고쳐 주세요. 모범 배선으로 비교할 수도 있습니다.';return false}
function digitView(value,n=2){const digits=String(value).padStart(n,'0');return `<div style="display:flex;gap:8px">${[...digits].map(d=>`<div style="width:105px">${segSvg(d)}</div>`).join('')}</div><span>${digits}</span>`}
function renderSim(){let html='';if(pi===0)html='<button id="swStart">시작</button><button id="swStop">정지</button><button id="swReset">00 초기화</button><button id="swPulse">1초 펄스</button>';if(pi===1)html='<button id="parkIn">입차 +1대</button><button id="parkOut">출차 −1대</button><button id="parkReset">집계 초기화</button>';if(pi===2)html='<button id="reactionStart">준비 / 다시 하기</button><button id="reactionHit">반응!</button>';if(pi===3)html='<button id="trafficStart">신호등 시작</button><button id="trafficStop">정지</button><button id="trafficPulse">1초 진행</button>';if(pi===4)html='<button id="rouletteStart">전체 회전</button><button id="stop0">1번 정지</button><button id="stop1">2번 정지</button><button id="stop2">3번 정지</button>';$('simControls').innerHTML=html;const output=$('simDisplay'),msg=$('simMessage');
if(pi===0){simState.count=0;const show=()=>{output.innerHTML=digitView(simState.count);msg.textContent=`${simState.count}초 · 두 자리 BCD 출력 · 99 다음 00`};const tick=()=>{simState.count=(simState.count+1)%100;show()};$('swStart').onclick=()=>{if(!canRun())return;safeStop();show();simulation=setInterval(tick,1000)};$('swStop').onclick=()=>{safeStop();msg.textContent='정지 · 시작을 누르면 이어서 측정'};$('swReset').onclick=()=>{if(!canRun())return;safeStop();simState.count=0;show()};$('swPulse').onclick=()=>{if(canRun()){safeStop();tick()}}}
if(pi===1){simState.entered=0;simState.exited=0;const show=()=>{const n=simState.entered-simState.exited;output.innerHTML=`<div class="parking-stats"><strong>현재 주차 ${n}대 / 99대</strong>${digitView(n)}<span>누적 입차 <b>${simState.entered}</b>대</span><span>누적 출차 <b>${simState.exited}</b>대</span><span>잔여 공간 <b>${99-n}</b>대</span></div>`;};show();$('parkIn').onclick=()=>{if(!canRun())return;if(simState.entered-simState.exited>=99){msg.textContent='만차! 입차 불가 · 집계는 증가하지 않습니다.';return}simState.entered++;show();msg.textContent='입차 1대 처리 · UP 펄스'};$('parkOut').onclick=()=>{if(!canRun())return;if(simState.entered===simState.exited){msg.textContent='현재 0대 · 출차 불가 · 집계는 증가하지 않습니다.';return}simState.exited++;show();msg.textContent='출차 1대 처리 · DOWN 펄스'};$('parkReset').onclick=()=>{if(!canRun()||!confirm('입차·출차 누적 집계와 현재 주차 대수를 모두 0으로 초기화할까요?'))return;simState.entered=simState.exited=0;show();msg.textContent='집계 초기화 완료'};}
if(pi===2){simState.phase='idle';$('reactionStart').onclick=()=>{if(!canRun())return;safeStop();simState.phase='wait';output.textContent='준비… 기다리세요';msg.textContent='GO가 뜨면 반응 버튼을 누르세요.';simulation=setTimeout(()=>{simState.phase='go';simState.go=performance.now();output.textContent='GO!';msg.textContent='지금 누르세요.';simulation=setTimeout(()=>{simState.phase='timeout';output.textContent='범위 초과';msg.textContent='두 자리 범위는 0.00~0.99초입니다.'},1000)},1000+Math.random()*2000)};$('reactionHit').onclick=()=>{if(!canRun())return;if(simState.phase==='wait'){safeStop();simState.phase='false';output.textContent='부정 출발';msg.textContent='GO 전에 눌렀어요. 준비 버튼으로 다시 시작하세요.'}else if(simState.phase==='go'){let cs=Math.floor((performance.now()-simState.go)/10);safeStop();simState.phase='done';if(cs>99){output.textContent='범위 초과';return}output.innerHTML=digitView(cs);msg.textContent=`${(cs/100).toFixed(2)}초 (${cs*10}ms, 10ms 단위). 브라우저·입력 지연을 포함한 교육용 측정입니다.`}else msg.textContent='준비 버튼을 눌러 새 게임을 시작하세요.'}}
if(pi===3){simState.stage=0;simState.left=10;const show=()=>{output.innerHTML=`${['red','green','yellow'].map((c,i)=>`<span class="traffic-dot ${i===simState.stage?c:''}"></span>`).join('')} ${['빨강','초록','노랑'][simState.stage]} ${String(simState.left).padStart(2,'0')}`;msg.textContent='빨강 10초 → 초록 10초 → 노랑 3초 반복. 00 검출 순간 다음 시간을 로드합니다.'};const tick=()=>{simState.left--;if(simState.left===0){simState.stage=(simState.stage+1)%3;simState.left=[10,10,3][simState.stage]}show()};$('trafficStart').onclick=()=>{if(!canRun())return;safeStop();show();simulation=setInterval(tick,1000)};$('trafficStop').onclick=safeStop;$('trafficPulse').onclick=()=>{if(canRun()){safeStop();tick()}}}
if(pi===4){simState.digits=[0,0,0];simState.running=[false,false,false];const show=()=>{output.innerHTML=digitView(simState.digits.join(''),3);msg.textContent=simState.running.some(Boolean)?'회전 중 · 각 정지 버튼으로 한 자리씩 멈추세요.':simState.digits.every(x=>x===7)?'777 당첨!':'세 자리 정지 · 다시 도전하세요.'};$('rouletteStart').onclick=()=>{if(!canRun())return;safeStop();simState.running=[true,true,true];show();simulation=setInterval(()=>{simState.digits=simState.digits.map((v,i)=>simState.running[i]?(v+1)%10:v);show()},65)};[0,1,2].forEach(i=>$('stop'+i).onclick=()=>{if(!canRun())return;simState.running[i]=false;if(!simState.running.some(Boolean))safeStop();show()})}}
renderProject();window.addEventListener('resize',drawWires);document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>{safeStop();$('timerStop').click();if(a.dataset.page==='step5')requestAnimationFrame(drawWires)}));
// Normalize all labels to Korean.
document.querySelectorAll('#step3 select').forEach(el=>{if(el.parentNode.firstChild.nodeType===3)el.parentNode.firstChild.textContent='표시 숫자 '});

function connectionText(key){const matches=k=>k===key||k.startsWith(key+'.');const wires=connections.filter(w=>w.some(matches));return (key.includes('.')?portLabel(key):projects[pi].parts.find(p=>p.id===key)?.name)+' — '+(wires.length?wires.map(w=>w.map(portLabel).join(' ↔ ')).join(' / '):'실제 연결 없음');}
function inspectConnection(key){const box=$('connectionInfo');if(!box)return;box.textContent=key?connectionText(key):'부품 제목이나 단자에 마우스를 올리거나 키보드 초점을 맞추면 실제 연결 정보가 표시됩니다.';const match=k=>key&&(k===key||k.startsWith(key+'.'));const ids=connections.map((w,i)=>w.some(match)?i:-1).filter(i=>i>=0);document.querySelectorAll('#projectWires path').forEach(el=>{el.classList.toggle('wire-focus',ids.includes(+el.dataset.wire));el.classList.toggle('wire-muted',!!key&&!ids.includes(+el.dataset.wire));});document.querySelectorAll('.node-port').forEach(el=>el.classList.toggle('port-focus',!!key&&(match(el.dataset.port)||ids.some(i=>connections[i].includes(el.dataset.port)))));}

// V4: project IC reference library.
const projectIcPanel=document.createElement('section');
projectIcPanel.className='lab-box';
projectIcPanel.innerHTML=`<h2>심화부품</h2><p>기본 IC와 중복되지 않는 심화부품입니다. 아래 칩을 펼쳐 기능과 핀을 확인하세요. DIP 윗면 기준이며 실제 제조사 데이터시트를 우선합니다. 74192/74LS192와 74HC192는 같은 십진 카운트 기능 계열이지만 전기적 규격은 다릅니다.</p>`;
const projectIcDocs=[
['74192 / 74HC192 · 십진 업/다운 카운터',['B','QB','QA','DOWN','UP','QC','QD','GND','D','C','/PL','/CARRY','/BORROW','MR','A','VCC'],'0~9를 BCD로 출력합니다. UP(5)의 상승 에지에서 증가하며 DOWN(4)은 HIGH, DOWN의 상승 에지에서 감소하며 UP은 HIGH여야 합니다. 두 클록을 동시에 구동하지 않습니다. MR(14)=HIGH면 0으로 초기화, /PL(11)=LOW면 A~D 병렬값을 로드합니다. 평소 MR=LOW, /PL=HIGH입니다. QA가 최하위 비트입니다. CARRY(12), BORROW(13)는 LOW 활성 자리올림·자리내림 출력입니다.','스톱워치, 주차장, 반응 게임, 신호등, 룰렛'],
['CD4511 · BCD→7세그먼트',['B','C','/LT','/BI','LE','D','A','VSS','e','d','c','b','a','g','f','VDD'],'A~D BCD를 a~g로 변환합니다. 공통 캐소드 표시기와 사용하며 각 세그먼트에 개별 전류 제한 저항을 둡니다. LE=LOW는 입력 추종, HIGH는 저장. /LT=LOW는 램프 테스트, /BI=LOW는 소등입니다. 일반 표시는 LE=LOW, /LT=/BI=HIGH입니다.','모든 프로젝트의 숫자 표시'],
['74HC74 · D 플립플롭',['/CLR1','D1','CLK1','/PRE1','Q1','/Q1','GND','/Q2','Q2','/PRE2','CLK2','D2','/CLR2','VCC'],'상승 클록 에지에서 D를 저장하는 플립플롭 2개입니다. /PRE와 /CLR는 비동기 LOW 활성이고 평소 HIGH로 둡니다. 둘을 동시에 LOW로 만들지 않습니다.','반응 게임의 RUN 기억, 신호등 상태 기억'],
['74HC14 · 슈미트 트리거 인버터',['1A','1Y','2A','2Y','3A','3Y','GND','4Y','4A','5Y','5A','6Y','6A','VCC'],'입력 전압 상승·하강 시 서로 다른 임계값을 사용합니다. RC와 함께 버튼 접점 튐과 느린 신호를 정리합니다. 출력은 입력의 반전이므로 펄스 극성에 주의합니다.','주차장 센서·버튼 펄스 정리'],
];
projectIcPanel.innerHTML+=projectIcDocs.map(([name,pins,desc,use])=>`<details><summary>${name}</summary><div class="lab-grid">${chipMap(name,pins)}<div><h3>기능과 연결</h3><p>${desc}</p><p><b>5단계 활용:</b> ${use}</p></div></div></details>`).join('');
$('step2').append(projectIcPanel);
// Materials list also exposes live, actual connection information.
$('projectArea').addEventListener('mouseover',e=>{const m=e.target.closest('.material');if(m){m.title=connectionText(m.dataset.part);inspectConnection(m.dataset.part)}});
$('projectArea').addEventListener('focusin',e=>{const m=e.target.closest('.material');if(m)inspectConnection(m.dataset.part)});
